import './globals.css'
import {Navbar} from './Navbar'
import {Footer} from './Footer'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <div className="pt-[75px] flex text-center justify-center items-center">
        {children}
        </div>
        <Footer/>
      </body>
    </html>
  )
}
